using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace App.WinForms
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

       

        private void btnRefresh(object sender, EventArgs e)
        {
            MessageBox.Show("Refresh Button Clicked");
        }

        private void lblUsername(object sender, EventArgs e)
        {
          

        }
    }
}
//Developer code
//partial class means that the class definition can be split across multiple files.
//In this case, Form1 is defined in both Form1.cs and Form1.Designer.cs.
//The Form1.Designer.cs file contains the code generated by the Windows Forms designer, while Form1.cs contains the code written by the developer.
//This allows for a clear separation between the auto-generated code and the developer's custom code.